### ISSUE TITLE
native2ascii.py 中的ascii()函数会出错

### ISSUE THREAD

**Issue by jhack77** [Jythoner/pycharm#2]
E:\pycharm-master>python native2ascii.py
Traceback (most recent call last):
  File "native2ascii.py", line 50, in <module>
    transcoding(i)
  File "native2ascii.py", line 23, in transcoding
    text = ascii(line.decode().replace('\n', ""))
NameError: global name 'ascii' is not defined

如上所示：不知道你的环境是怎样的？

**Comment by Jythoner** [comment]
需要python3.0以上才能运行该文件

**Comment by Ramon403** [comment]
感谢楼上解惑！

**Comment by wangganyu188** [comment]
请问pycharm 中文输入法支持，怎么做
